language: node_js
dist: xenial
node_js:
  - 0.10
  - 4
  - 6
  - 7
  - 8
  - 9
  - 11
  - 12
  - 13
  - 13
  - 14
jobs:
  include:
    - dist: focal
      node_js: 4
    - dist: focal
      node_js: 5
    - dist: focal
      node_js: 6
    - dist: focal
      node_js: 7
    - dist: focal
      node_js: 8
    - dist: focal
      node_js: 9
    - dist: focal
      node_js: 10
    - dist: focal
      node_js: 11
    - dist: focal
      node_js: 12
    - dist: focal
      node_js: 13
    - dist: focal
      node_js: 14
script:
  - npm run lint
  - npm run test
  - npm run test-coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf coverage
  
