---
language: node_js
cache: npm

os:
  - linux
  - dist: focal

matrix:
    include:
        - dist: trusty
        - dist: xenial
        - dist: bionic

node_js:
  - 0.10
  - 4
  - 6
  - 7
  - 8
  - 9
  - 11
  - 12
  - 13
  - 13
  - 14
  - node # latest stable Node.js release
  - lts/* # latest LTS Node.js release

script:
  - npm run lint
  - npm run test
  - npm run test-coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf coverage
  
